export const validIncidentPayload = {
  data: {
    type: "incidents",
    attributes: {
      reportDate: "2026-02-20T10:00:00.000Z",
      version: "1.0",
      classification: "CONFIDENTIEL",
      status: "resolved",
      applicationName: "Portail Admin",
      applicationDetail: "Module gestion utilisateurs",
      environment: "production",
      clientCode: "IPBW",
      clientName: "IPBW SA",
      reportedBy: "Support N1",
      recipientName: "Direction IT",
      recipientOrg: "IPBW",
      legalContext: "Incident technique sans impact données personnelles.",
      serviceName: "API Auth",
      deployedVersion: "2.4.1",
      incidentStartAt: "2026-02-19T08:00:00.000Z",
      incidentEndAt: "2026-02-19T12:30:00.000Z",
      detectedAt: "2026-02-19T08:15:00.000Z",
      resolvedAt: "2026-02-19T12:30:00.000Z",
      resolutionDurationMinutes: 255,
      technicalLeadId: null,
      description: "Défaillance du service d'authentification.",
      descriptionSections: [{ title: "Code défaillant", detail: "NullPointerException" }],
      personalDataImpacted: true,
      specialCategoryData: false,
      apdNotificationRequired: false,
      impactSummary: "50 comptes administrateurs exposés temporairement",
      impactDetails: null,
      severityOperational: "high",
      severityCompliance: "medium",
      severityOverall: "high",
      affectedPersonsCount: 50,
      affectedPatientsCount: null,
      immediateCause: "Régression après déploiement",
      contributingFactors: ["Absence de test de non-régression"],
      correctiveActions: [
        {
          order: 1,
          title: "Rollback",
          detail: "Retour version 2.4.0",
          completedAt: "2026-02-19T13:00:00.000Z",
        },
      ],
      preventiveMeasures: ["Renforcer la couverture de tests"],
      communicationPlan: [
        { audience: "clients", channel: "email", message: "Information incident" },
      ],
      conclusion: "Incident résolu, pas de notification APD requise.",
      timelineEvents: [
        { date: "2026-02-19", time: "08:00", event: "Début incident" },
        { date: "2026-02-19", time: "12:30", event: "Résolution" },
      ],
      accessLogs: null,
      issuerSignature: { name: "RSSI", date: "2026-02-20" },
      recipientSignature: { name: "DSI", date: "2026-02-20" },
    },
  },
};

export const validOcmPayload = {
  data: {
    type: "incidents",
    attributes: {
      ...validIncidentPayload.data.attributes,
      reportDate: "2026-04-03T10:00:00.000Z",
      clientCode: "OCM",
      clientName: "OCM Clinique",
      status: "closed",
      specialCategoryData: true,
      personalDataImpacted: true,
      apdNotificationRequired: true,
      impactSummary: "Accès non autorisé à des dossiers patients",
      severityCompliance: "critical",
      severityOverall: "critical",
      affectedPatientsCount: 12,
      correctiveActions: [
        { phase: "Phase 1", order: 1, title: "Containment", detail: "Révocation accès" },
        { phase: "Phase 2", order: 2, title: "Investigation", detail: "Analyse logs" },
      ],
      accessLogs: [
        {
          date: "2026-04-01",
          user: "jdoe",
          email: "jdoe@ocm.be",
          files: "dossiers/*.pdf",
          count: 3,
        },
      ],
      conclusion: "Notification APD en cours d'évaluation.",
      timelineEvents: [
        { date: "2026-04-01", time: "14:00", event: "Détection anomalie" },
        { date: "2026-04-03", time: "09:00", event: "Clôture investigation" },
      ],
    },
  },
};
